# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepingQuality', models.CharField(max_length=7)),
                ('tirednessFeeling', models.CharField(max_length=7)),
                ('date', models.DateTimeField()),
                ('uuid', models.CharField(max_length=32)),
            ],
        ),
    ]
