# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0002_calendar_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 9, 17, 47, 36, 4412, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 9, 17, 47, 47, 692458, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
