# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0003_auto_20160209_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
