# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0004_auto_20160217_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='userId',
            new_name='user',
        ),
    ]
