# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0005_auto_20160217_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='sleepingQuality',
            field=models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('regular', 'regular')], max_length=7),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='tirednessFeeling',
            field=models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('regular', 'regular')], max_length=7),
        ),
    ]
