# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0006_auto_20160217_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
