# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0007_auto_20160223_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid3, editable=False),
        ),
    ]
