# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sleepCalendar', '0008_auto_20160301_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleepingQuality', models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('regular', 'regular')], max_length=7)),
                ('tirednessFeeling', models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('regular', 'regular')], max_length=7)),
                ('day', models.DateTimeField()),
                ('uuid', models.UUIDField(default=uuid.uuid3, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='user',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
