# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0009_auto_20160301_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='id',
        ),
        migrations.AlterField(
            model_name='day',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid3(uuid.NAMESPACE_DNS, 'name'), editable=False, serialize=False),
        ),
    ]
