# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0010_auto_20160301_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='day',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid3(uuid.NAMESPACE_DNS, 'name'), editable=False),
        ),
    ]
