# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0011_auto_20160302_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
