# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0012_auto_20160302_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
