# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0013_auto_20160302_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.AutoField(serialize=False, verbose_name='ID'),
        ),
    ]
