# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepCalendar', '0014_auto_20160624_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
